print("Hello, Git!")
print("Learning staged changes!")
print("Version 1.1 feature added!")
print("Remote branch feature")
print("Pull request demo feature")
print("Rebase demo feature")
print("Cherry-pick feature")
print("Version A")
print("Version B")
